# -*- coding: utf-8 -*-
"""Statistics case study project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pKiMdBxC2JS8ttGwNWInhB1SGAdsqEFV
"""

print("Hello world")

# importing all required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data =  pd.read_csv("/content/Employee Dataset.csv")  #loading the data set into the notebook

data.head()

data.tail()

data.shape

data.index

data.columns

data.info()

"""Tast 1-

load the data and study its features such as

1.  no. of the employees
2.  no. of featurs
1.  types of features




"""



"""Task 2-



*   a scatter plot  of employee , age , salary, healthy eating, and etc.
*   plot of groups
*   histogram of emp sal




"""

# Create a Scatter plot indicating the salary against age
plt.figure(figsize=(10, 6))

sns.scatterplot(data=data, x='age', y='salary', color = "blue",
                edgecolor = 'linen', alpha = 0.5)
plt.title('Age vs Salary', fontweight = 'bold')
plt.xlabel('Age')
plt.ylabel('Salary')
plt.grid(True)
plt.show()

"""Observation


we observ that in general , there is a relationshio between age and salary of emp.
age increases , the salary also increased, though ther are some outasliers present as well.
"""

# Create the scatter plot of the  healthy_eating and active_lifestyle.

plt.figure(figsize=(10,8))

sns.scatterplot(data=data, x= 'healthy_eating', y ='active_lifestyle',
                color = 'red', edgecolor = 'linen', alpha= 0.5)

plt.title("Healthy_Eating  vs active_lifestyle", fontweight = 'bold')
plt.xlabel("healthy_eating")
plt.ylabel("active_lifestyle")
plt.show()

"""Observation

we observ that in general , there is a relationship between healthy_eating and active_lifestyle of employee, healthy eating increases , the active lifestyle also increases.
"""



# Create the scatter plot agains the sal and healthy eating
plt.figure(figsize=(10, 6))
sns.scatterplot(data=data, x='healthy_eating', y='salary', color='black', edgecolor='linen', alpha=0.7)
plt.title('Healthy Eating vs Salary', fontweight='bold')
plt.xlabel('Healthy Eating Score')
plt.ylabel('Salary')
plt.show()

"""Observation

as we found that the healthy eating increases the salary also increases.
"""

# Create a count plot for the groups features

plt.figure(figsize=(10,6))

sns.countplot(data=data, x= 'groups', hue='groups', edgecolor='linen', alpha=0.7)

plt.title("Count plots of groups", fontweight='bold')
plt.xlabel("groups")
plt.ylabel("Count")
plt.show()

"""Observation


we see that most employees are belongs to the group A and O, while group A has the most no of employee.
"""

# Create histogram about salary featues

plt.figure(figsize= (10,6))

sns.histplot(data=data, x = "salary",
             color= "yellow" ,edgecolor = "black", bins = 10, )
plt.title("salary", fontweight = "bold")
plt.xlabel("Salary")
plt.ylabel("Count")
plt.show()

"""Observation


We see that the salaries are not uniform , which is not neccessarily discrepency
 but we do observe there are employee with slareies on either extremities of the problem

 Based on th histogram we can use that the count of highest earning employee is very less.
"""



"""Task 3-

subset dataset based on the threshold


1.  employee with healthy eating is greater thatn 8
2.   employee with sal  less than 1000


1.   employee with healthy eating greater than 8 and sal is 1000




"""

#  employee health eating is greater than 8

sub1= data[data['healthy_eating']>8]
sub1

sub2= data[data['salary']<1000]
sub2

sub = data[(data['healthy_eating']>8) & (data['salary']<1000)]

sub

"""Observation


1.  the only emoloyee seeming facing a discrepency in sal as compared to healthy is employee who id is 26
2.   the employee with id 26 has sal 700


"""



"""**Final Conlcusion**

Form the data, we can use siple visualization to get sense of how data are distributed.

we can conduct preliminary analyses by subsetting data set using well thought out threshold and condition.
"""